### PR TITLE
Draft: Upgrade to version 3.14.0

### PR DESCRIPTION
**Pull request by glesys-andreas**
Hi, 

Got the latest version of the software running, some errors in the console but everything seems to be working so far.
If anyone have suggestions to solve these it would be appreciated.
```
Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/Nagstamon/Config.py", line 710, in KeyringAvailable
    import secretstorage
  File "/app/lib/python3.11/site-packages/secretstorage/__init__.py", line 13, in <module>
    from secretstorage.collection import Collection, create_collection, \
  File "/app/lib/python3.11/site-packages/secretstorage/collection.py", line 24, in <module>
    from secretstorage.item import Item
  File "/app/lib/python3.11/site-packages/secretstorage/item.py", line 17, in <module>
    from secretstorage.util import DBusAddressWrapper, \
  File "/app/lib/python3.11/site-packages/secretstorage/util.py", line 23, in <module>
    from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
  File "/app/lib/python3.11/site-packages/cryptography/hazmat/primitives/ciphers/__init__.py", line 11, in <module>
    from cryptography.hazmat.primitives.ciphers.base import (
  File "/app/lib/python3.11/site-packages/cryptography/hazmat/primitives/ciphers/base.py", line 10, in <module>
    from cryptography.exceptions import (
  File "/app/lib/python3.11/site-packages/cryptography/exceptions.py", line 9, in <module>
    from cryptography.hazmat.bindings._rust import exceptions as rust_exceptions
ImportError: cannot import name 'exceptions' from 'cryptography.hazmat.bindings._rust' (unknown location)
cannot import name 'exceptions' from 'cryptography.hazmat.bindings._rust' (unknown location)
cannot import name 'exceptions' from 'cryptography.hazmat.bindings._rust' (unknown location)
qt.qpa.qgnomeplatform: Could not find color scheme  ""
Qt: Session management error: Could not open network socket
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
qt.multimedia.ffmpeg.libsymbolsresolver: Couldn't load VAAPI library
```

### CODE REVIEW

**Comment by HenriWahl** [comment]
@glesys-andreas thanks for taking care of this pretty outdated flatpak!
How did Rust came in here?

**Comment by HenriWahl** [comment]
@glesys-andreas how can I try it? The hint from @flathubbot does not work for me.

**Comment by glesys-andreas** [comment]
> @glesys-andreas thanks for taking care of this pretty outdated flatpak! How did Rust came in here?

I think it was only the cryptography packaged that required rust when compiling: https://cryptography.io/en/latest/faq/#why-does-cryptography-require-rust and https://cryptography.io/en/3.4.2/installation.html#building-cryptography-on-linux , but i'm currently trying to build the package with the precompiled version of cryptography instead.

**Comment by glesys-andreas** [comment]
> @glesys-andreas how can I try it? The hint from @flathubbot does not work for me.

Aaah, yeah that didn't work for me either, in that case I think you can follow the README.md ;) , it requires some runtimes for flatpak to be installed first though.

**Comment by HenriWahl** [comment]
@glesys-andreas it does not work with Qt6? Would be cool if it woulde because of better Wayland support.

**Comment by glesys-andreas** [comment]
@HenriWahl : I made a new commit, switching to QT6:
image

**Comment by glesys-andreas** [comment]
@HenriWahl  Is it possible to make the icon a square? Ref: https://docs.flatpak.org/fr/latest/conventions.html
https://github.com/HenriWahl/Nagstamon/blob/master/Nagstamon/resources/nagstamon.svg?short_path=15dce5b#L13-L14
I'm currently making a "fix" for it here:
https://github.com/glesys-andreas/de.ifw_dresden.nagstamon/blob/upgradeto_3_14/de.ifw_dresden.nagstamon.yml#L81

**Comment by HenriWahl** [comment]
@glesys-andreas great job. Runs now for me too. :+1: 

I just noted that there is apparently no access to GNOME keyring - do you know if this is an extra permission?

Maybe just let's live with you square icon "fix" as it will just be relevant for the Flatpak stuff.

I also get these cryptic hazmat exceptions but have no idea what they are about.

**Comment by glesys-andreas** [comment]
@HenriWahl Do you mean that you want the flatpak app to access your "global" keyring on the system? I've experimented a bit with that but couldn't get it to work. I think its basically down to design choices, flatpak apps are meant to be run sandboxed and have access to as little information about the system as possible.

Solved the cryptic hazmat exceptions, i had imported the cryptography library in two different modules :see_no_evil:

**Comment by HenriWahl** [comment]
@glesys-andreas great news according the crypto problem 👍.

And yes, I mean the local global keyring. I searched a little bit and think, it might depend on dbus permissions?

**Comment by HenriWahl** [comment]
@glesys-andreas great - I am going to test ASAP.

**Comment by HenriWahl** [comment]
@glesys-andreas I tried but get this:

```
flatpak install --user https://dl.flathub.org/build-repo/93448/de.ifw_dresden.nagstamon.flatpakref
Fehler: Can't load uri https://dl.flathub.org/build-repo/93448/de.ifw_dresden.nagstamon.flatpakref: Server returned status 404
```
Do you have another working link?

**Edit:** I built it from repo and got it running. Works fine with local key vault! :+1:

**Comment by glesys-andreas** [comment]
Nice!
Noticed that the appdata.xml also needs updating with the new version for Flathub. Is that something you do or should i create a PR?

**Comment by HenriWahl** [comment]
@glesys-andreas good point. If you would like to do it it would be great - I might find the time somewhen later.

**Comment by glesys-andreas** [comment]
@HenriWahl  Leaving this PR and continuing here:  https://github.com/flathub/de.ifw_dresden.nagstamon/pull/11

**Pull request merged**
